[font]
size = 14

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[window]
opacity = 0.75

[window.padding]
x = 15
y = 15

[window.dimensions]
columns = 240
lines = 50

[cursor.style]
shape = "Underline"
blinking = "Always"
